version: '3.8'

services:
  swe-agent:
    image: swe-agent:latest
    container_name: swe-agent_assignment
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
    ports:
      - "8000:8000"
